name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-x64-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Test Start
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="

      - name: Install Dependencies
        run: |
          sudo apt-get install cmake
          sudo apt-get install build-essential
          sudo apt-get install libboost-dev libboost-all-dev
          sudo apt-get install libzmq3-dev python3-zmq
          sudo apt-get install openssl libssl-dev

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=$PWD
          cd $HDTN_SOURCE_ROOT
          mkdir build
          cd build
          cmake ..
          make -j8

          # - name: Unit Tests
          #run: |
          #export HDTN_SOURCE_ROOT=$PWD
          #cd $HDTN_SOURCE_ROOT
          #cd build
          #./tests/unit_tests/unit-tests

      # - name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  debian-x64-test:
    runs-on: [self-hosted, Linux, X64, debian]

    steps:
      - uses: actions/checkout@v3

      - name: Display Test Start
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="

      - name: Build HDTN
        run: |
          export HDTN_SOURCE_ROOT=/home/hdtn/HDTN_LATEST/HDTN
          cd $HDTN_SOURCE_ROOT
          git pull
          cd $HDTN_SOURCE_ROOT/build
          cmake ..
          make -j8

      - name: Unit Tests
        run: |
          export HDTN_SOURCE_ROOT=/home/hdtn/HDTN_LATEST/HDTN
          cd $HDTN_SOURCE_ROOT/build
          ./tests/unit_tests/unit-tests

      #- name: Integration Tests
      #  run: |
      #    export HDTN_SOURCE_ROOT=$PWD
      #    cd $HDTN_SOURCE_ROOT
      #    cd build
      #    ./tests/integrated_tests/integrated-tests

  coverity-test:

    runs-on:  [self-hosted, Linux, X64, cov-analysis]

    steps:
      - uses: actions/checkout@v3
      
      - name: Coverity Scan
        run: |
          export PATH=/home/hdtn/cov-analysis-linux64-2022.6.1/bin:$PATH
          export HDTN_SOURCE_ROOT=/home/hdtn/HDTN_LATEST/HDTN
          cd $HDTN_SOURCE_ROOT
          git pull
          cd $HDTN_SOURCE_ROOT/build
          make clean
          cov-build --dir idir make -j8
          cov-analyze --dir idir --all --enable-constraint-fpp --enable-fnptr --enable-virtual --strip-path $HDTN_SOURCE_ROOT
          cov-commit-defects --dir idir --url  ${{COVERITY_BUILD}} --stream HDTN-master --auth-key-file /home/hdtn/auth.key
